data:
  dataset_path: "data/pakistan_house_price.csv"
  target: "price"

prepare:
  random_seed: 42

features:
  test_size: 0.2
  random_state: 42
  numeric_features: ["baths", "bedrooms", "latitude", "longitude", "Area Size"]
  categorical_features: ["property_type", "city", "province_name", "Area Category"]

train:
  model_type: "random_forest"
  n_estimators: 100
  max_depth: 10
  random_state: 42

evaluate:
  metrics: ["mse", "mae", "r2"]